site_name: Pr치ctica Unidad 1 PPS - HectorBG
nav:
  - Indice: index.md
  - Ejecuci칩n y depuraci칩n: ejecucion-y-depuracion.md
  - Pruebas: pruebas.md
  - Sandbox: sandbox.md
  - Reflexi칩n personal: reflexion.md
docs_dir: markdown
